apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-cluster-admin
  labels:
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: helm
      name: tiller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: helm
        name: tiller
    spec:
      serviceAccountName: tiller
      containers:
        - name: tiller
          image: gcr.io/kubernetes-helm/tiller:v2.14.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TILLER_NAMESPACE
              value: kube-system
          ports:
            - containerPort: 44134
              name: tiller
          livenessProbe:
            httpGet:
              path: /liveness
              port: 44135
            initialDelaySeconds: 25
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 44135
            initialDelaySeconds: 15
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  selector:
    app: helm
    name: tiller
  ports:
    - name: tiller
      port: 44134
      targetPort: tiller
  type: ClusterIP