version: "3"
services:
  multi-factor-authenticator:
    image: szymongib/multi-factor-authenticator:master
    ports:
      - 8000:8000
    command:
      ./core
    volumes:
      - ./core:/config
    environment:
      - APP_EXTERNAL_API_PORT=8000
      - APP_JWT_VALIDITY_TIME=10m
      - APP_JWT_SECRET_KEY=secret
      - APP_AUTHENTICATIONS_CACHE_VALIDITY_TIME=10m
      - APP_AUTHENTICATION_CONFIG_FILE=./config/config.json
      - APP_TLS_CERTIFICATE_PATH=./config/certificates/tls.crt
      - APP_TLS_KEY_PATH=./config/certificates/tls.key
      - APP_ID_TOKEN_RSA_PRIVATE_KEY_PATH=./config/idToken/key.pem
      - APP_ID_TOKEN_VALIDITY_TIME=1h
      - APP_CA_CERTIFICATE_PATH=./config/certificates/ca.crt
      - APP_CA_KEY_PATH=./config/certificates/ca.key
      - APP_CORS_ALLOW_ALL=true
      - APP_DATABASE_USER=postgres
      - APP_DATABASE_PASSWORD=password
      - APP_DATABASE_HOST=core-database
      - APP_DATABASE_PORT=5432
      - APP_DATABASE_NAME=postgres
      - APP_DATABASE_SSL_MODE=disable
      - APP_DATABASE_SCHEMA_FILE_PATH=/assets/database/schema.sql

  password-authenticator:
    image: szymongib/password-authenticator:master
    command: ./passwordauthenticator

  core-database:
    image: postgres:12

