version: "3"
services:
  user-service:
    image: szymongib/user-service:master
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
    command:
      ./userservice --authenticationConfigFile ./config/config.json
      --tlsCertificatePath ./config/certificates/tls.crt
      --tlsKeyPath ./config/certificates/tls.key
      --caCertificatePath ./config/certificates/ca.crt
      --caKeyPath ./config/certificates/ca.key
    volumes:
      - ./user-service:/config

  password-authenticator:
    image: szymongib/password-authenticator:master
    command: ./passwordauthenticator

  gps-authenticator:
    image: kfurgol/gps-auth:latest
    command: ./passwordauthenticator

  pattern-authenticator:
    image: kfurgol/pattern-auth:prod
    command: ./passwordauthenticator
