apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-external-api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.core.externalApiPort }}
      protocol: TCP
      name: http-api-port
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-reverse-proxy
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.core.reverseProxyPort}}
      protocol: TCP
      name: http-proxy-port
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Name }}
